# Generated by Django 5.1.2 on 2024-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais_origen', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
